packages:
  - src/**/*
allowBuilds:
  '@biomejs/biome': true
  canvas: false
  core-js: false
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - imapflow@1.7.8
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
