/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppRole = IDL.Variant({
  'qc' : IDL.Null,
  'admin' : IDL.Null,
  'production' : IDL.Null,
  'sales' : IDL.Null,
  'accounts' : IDL.Null,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DeliveryChallan = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'dcNo' : IDL.Text,
  'createdAt' : Time,
  'soId' : IDL.Text,
  'customerId' : IDL.Text,
  'items' : IDL.Text,
});
export const EmployeeProfile = IDL.Record({
  'name' : IDL.Text,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'roles' : IDL.Vec(AppRole),
});
export const EnquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'quoted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : EnquiryStatus,
  'createdAt' : Time,
  'description' : IDL.Text,
  'enqNo' : IDL.Text,
  'targetDate' : Time,
  'customerId' : IDL.Text,
  'items' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'customerId' : IDL.Text,
  'invNo' : IDL.Text,
});
export const JobCard = IDL.Record({
  'id' : IDL.Text,
  'drawingFileIds' : IDL.Vec(IDL.Text),
  'jobDescription' : IDL.Text,
  'createdAt' : Time,
  'soId' : IDL.Text,
  'jobNo' : IDL.Text,
  'customerId' : IDL.Text,
  'materialRequisitionStatus' : IDL.Text,
});
export const MaterialRequisition = IDL.Record({
  'id' : IDL.Text,
  'totalEstimatedCost' : IDL.Nat,
  'status' : IDL.Text,
  'mrNo' : IDL.Text,
  'createdAt' : Time,
  'jobId' : IDL.Text,
  'items' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'invoiceId' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Nat,
});
export const PurchaseOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
  'received' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : PurchaseOrderStatus,
  'poAmount' : IDL.Nat,
  'createdAt' : Time,
  'qtId' : IDL.Text,
  'customerId' : IDL.Text,
  'poRef' : IDL.Text,
  'poDate' : Time,
});
export const QuotationLineItem = IDL.Record({
  'hsn' : IDL.Text,
  'qty' : IDL.Nat,
  'desc' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const QuotationStatus = IDL.Variant({
  'sent' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'draft' : IDL.Null,
});
export const Quotation = IDL.Record({
  'id' : IDL.Text,
  'status' : QuotationStatus,
  'lineItems' : IDL.Vec(QuotationLineItem),
  'terms' : IDL.Text,
  'createdAt' : Time,
  'qtNo' : IDL.Text,
  'enqId' : IDL.Text,
  'gstAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Text,
  'gstRate' : IDL.Nat,
  'validUntil' : Time,
  'subtotal' : IDL.Nat,
});
export const SalesOrderLineItem = IDL.Record({
  'qty' : IDL.Nat,
  'desc' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const SalesOrderStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'dispatched' : IDL.Null,
  'inProduction' : IDL.Null,
  'readyToDispatch' : IDL.Null,
});
export const SalesOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : SalesOrderStatus,
  'lineItems' : IDL.Vec(SalesOrderLineItem),
  'createdAt' : Time,
  'poId' : IDL.Text,
  'qtId' : IDL.Text,
  'soNo' : IDL.Text,
  'deliveryDate' : Time,
  'customerId' : IDL.Text,
  'remarks' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'roles' : IDL.Vec(AppRole),
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignAppRoles' : IDL.Func([IDL.Principal, IDL.Vec(AppRole)], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'createDeliveryChallan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [DeliveryChallan],
      [],
    ),
  'createEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
  'createEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [Enquiry],
      [],
    ),
  'createInvoice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Invoice], []),
  'createJobCard' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [JobCard],
      [],
    ),
  'createMaterialRequisition' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [MaterialRequisition],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time],
      [Payment],
      [],
    ),
  'createPurchaseOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat],
      [PurchaseOrder],
      [],
    ),
  'createQuotation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(QuotationLineItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Text,
      ],
      [Quotation],
      [],
    ),
  'createSalesOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SalesOrderLineItem),
        Time,
        IDL.Text,
      ],
      [SalesOrder],
      [],
    ),
  'fileExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'generateDocNo' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDeliveryChallans' : IDL.Func(
      [],
      [IDL.Vec(DeliveryChallan)],
      ['query'],
    ),
  'getAllEmployeeProfiles' : IDL.Func(
      [],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllJobCards' : IDL.Func([], [IDL.Vec(JobCard)], ['query']),
  'getAllMaterialRequisitions' : IDL.Func(
      [],
      [IDL.Vec(MaterialRequisition)],
      ['query'],
    ),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
  'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getDeliveryChallan' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DeliveryChallan)],
      ['query'],
    ),
  'getEmployeeProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EmployeeProfile)],
      ['query'],
    ),
  'getEnquiry' : IDL.Func([IDL.Text], [IDL.Opt(Enquiry)], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getJobCard' : IDL.Func([IDL.Text], [IDL.Opt(JobCard)], ['query']),
  'getMaterialRequisition' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MaterialRequisition)],
      ['query'],
    ),
  'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
  'getPurchaseOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PurchaseOrder)],
      ['query'],
    ),
  'getQuotation' : IDL.Func([IDL.Text], [IDL.Opt(Quotation)], ['query']),
  'getSalesOrder' : IDL.Func([IDL.Text], [IDL.Opt(SalesOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasDrawing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEmployeeProfile' : IDL.Func([IDL.Text, EmployeeProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppRole = IDL.Variant({
    'qc' : IDL.Null,
    'admin' : IDL.Null,
    'production' : IDL.Null,
    'sales' : IDL.Null,
    'accounts' : IDL.Null,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DeliveryChallan = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'dcNo' : IDL.Text,
    'createdAt' : Time,
    'soId' : IDL.Text,
    'customerId' : IDL.Text,
    'items' : IDL.Text,
  });
  const EmployeeProfile = IDL.Record({
    'name' : IDL.Text,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'roles' : IDL.Vec(AppRole),
  });
  const EnquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'quoted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : EnquiryStatus,
    'createdAt' : Time,
    'description' : IDL.Text,
    'enqNo' : IDL.Text,
    'targetDate' : Time,
    'customerId' : IDL.Text,
    'items' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'customerId' : IDL.Text,
    'invNo' : IDL.Text,
  });
  const JobCard = IDL.Record({
    'id' : IDL.Text,
    'drawingFileIds' : IDL.Vec(IDL.Text),
    'jobDescription' : IDL.Text,
    'createdAt' : Time,
    'soId' : IDL.Text,
    'jobNo' : IDL.Text,
    'customerId' : IDL.Text,
    'materialRequisitionStatus' : IDL.Text,
  });
  const MaterialRequisition = IDL.Record({
    'id' : IDL.Text,
    'totalEstimatedCost' : IDL.Nat,
    'status' : IDL.Text,
    'mrNo' : IDL.Text,
    'createdAt' : Time,
    'jobId' : IDL.Text,
    'items' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'invoiceId' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Nat,
  });
  const PurchaseOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
    'received' : IDL.Null,
  });
  const PurchaseOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : PurchaseOrderStatus,
    'poAmount' : IDL.Nat,
    'createdAt' : Time,
    'qtId' : IDL.Text,
    'customerId' : IDL.Text,
    'poRef' : IDL.Text,
    'poDate' : Time,
  });
  const QuotationLineItem = IDL.Record({
    'hsn' : IDL.Text,
    'qty' : IDL.Nat,
    'desc' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const QuotationStatus = IDL.Variant({
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Quotation = IDL.Record({
    'id' : IDL.Text,
    'status' : QuotationStatus,
    'lineItems' : IDL.Vec(QuotationLineItem),
    'terms' : IDL.Text,
    'createdAt' : Time,
    'qtNo' : IDL.Text,
    'enqId' : IDL.Text,
    'gstAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Text,
    'gstRate' : IDL.Nat,
    'validUntil' : Time,
    'subtotal' : IDL.Nat,
  });
  const SalesOrderLineItem = IDL.Record({
    'qty' : IDL.Nat,
    'desc' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const SalesOrderStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'dispatched' : IDL.Null,
    'inProduction' : IDL.Null,
    'readyToDispatch' : IDL.Null,
  });
  const SalesOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : SalesOrderStatus,
    'lineItems' : IDL.Vec(SalesOrderLineItem),
    'createdAt' : Time,
    'poId' : IDL.Text,
    'qtId' : IDL.Text,
    'soNo' : IDL.Text,
    'deliveryDate' : Time,
    'customerId' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'roles' : IDL.Vec(AppRole),
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'assignAppRoles' : IDL.Func([IDL.Principal, IDL.Vec(AppRole)], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'createDeliveryChallan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [DeliveryChallan],
        [],
      ),
    'createEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
    'createEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [Enquiry],
        [],
      ),
    'createInvoice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Invoice], []),
    'createJobCard' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [JobCard],
        [],
      ),
    'createMaterialRequisition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [MaterialRequisition],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time],
        [Payment],
        [],
      ),
    'createPurchaseOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat],
        [PurchaseOrder],
        [],
      ),
    'createQuotation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(QuotationLineItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Text,
        ],
        [Quotation],
        [],
      ),
    'createSalesOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SalesOrderLineItem),
          Time,
          IDL.Text,
        ],
        [SalesOrder],
        [],
      ),
    'fileExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'generateDocNo' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDeliveryChallans' : IDL.Func(
        [],
        [IDL.Vec(DeliveryChallan)],
        ['query'],
      ),
    'getAllEmployeeProfiles' : IDL.Func(
        [],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllJobCards' : IDL.Func([], [IDL.Vec(JobCard)], ['query']),
    'getAllMaterialRequisitions' : IDL.Func(
        [],
        [IDL.Vec(MaterialRequisition)],
        ['query'],
      ),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
    'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getDeliveryChallan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DeliveryChallan)],
        ['query'],
      ),
    'getEmployeeProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EmployeeProfile)],
        ['query'],
      ),
    'getEnquiry' : IDL.Func([IDL.Text], [IDL.Opt(Enquiry)], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getJobCard' : IDL.Func([IDL.Text], [IDL.Opt(JobCard)], ['query']),
    'getMaterialRequisition' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MaterialRequisition)],
        ['query'],
      ),
    'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
    'getPurchaseOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PurchaseOrder)],
        ['query'],
      ),
    'getQuotation' : IDL.Func([IDL.Text], [IDL.Opt(Quotation)], ['query']),
    'getSalesOrder' : IDL.Func([IDL.Text], [IDL.Opt(SalesOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasDrawing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEmployeeProfile' : IDL.Func([IDL.Text, EmployeeProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };