/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'qc' : null } |
  { 'admin' : null } |
  { 'production' : null } |
  { 'sales' : null } |
  { 'accounts' : null };
export interface Customer {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'contactPerson' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface DeliveryChallan {
  'id' : string,
  'status' : string,
  'dcNo' : string,
  'createdAt' : Time,
  'soId' : string,
  'customerId' : string,
  'items' : string,
}
export interface EmployeeProfile {
  'name' : string,
  'photo' : [] | [Uint8Array],
  'roles' : Array<AppRole>,
}
export interface Enquiry {
  'id' : string,
  'status' : EnquiryStatus,
  'createdAt' : Time,
  'description' : string,
  'enqNo' : string,
  'targetDate' : Time,
  'customerId' : string,
  'items' : string,
}
export type EnquiryStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'quoted' : null } |
  { 'inProgress' : null };
export interface Invoice {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'customerId' : string,
  'invNo' : string,
}
export interface JobCard {
  'id' : string,
  'drawingFileIds' : Array<string>,
  'jobDescription' : string,
  'createdAt' : Time,
  'soId' : string,
  'jobNo' : string,
  'customerId' : string,
  'materialRequisitionStatus' : string,
}
export interface MaterialRequisition {
  'id' : string,
  'totalEstimatedCost' : bigint,
  'status' : string,
  'mrNo' : string,
  'createdAt' : Time,
  'jobId' : string,
  'items' : string,
}
export interface Payment {
  'id' : string,
  'createdAt' : Time,
  'invoiceId' : string,
  'paymentDate' : Time,
  'amount' : bigint,
}
export interface PurchaseOrder {
  'id' : string,
  'status' : PurchaseOrderStatus,
  'poAmount' : bigint,
  'createdAt' : Time,
  'qtId' : string,
  'customerId' : string,
  'poRef' : string,
  'poDate' : Time,
}
export type PurchaseOrderStatus = { 'cancelled' : null } |
  { 'confirmed' : null } |
  { 'received' : null };
export interface Quotation {
  'id' : string,
  'status' : QuotationStatus,
  'lineItems' : Array<QuotationLineItem>,
  'terms' : string,
  'createdAt' : Time,
  'qtNo' : string,
  'enqId' : string,
  'gstAmount' : bigint,
  'totalAmount' : bigint,
  'customerId' : string,
  'gstRate' : bigint,
  'validUntil' : Time,
  'subtotal' : bigint,
}
export interface QuotationLineItem {
  'hsn' : string,
  'qty' : bigint,
  'desc' : string,
  'unitPrice' : bigint,
  'amount' : bigint,
}
export type QuotationStatus = { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'draft' : null };
export interface SalesOrder {
  'id' : string,
  'status' : SalesOrderStatus,
  'lineItems' : Array<SalesOrderLineItem>,
  'createdAt' : Time,
  'poId' : string,
  'qtId' : string,
  'soNo' : string,
  'deliveryDate' : Time,
  'customerId' : string,
  'remarks' : string,
}
export interface SalesOrderLineItem {
  'qty' : bigint,
  'desc' : string,
  'unitPrice' : bigint,
  'amount' : bigint,
}
export type SalesOrderStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'dispatched' : null } |
  { 'inProduction' : null } |
  { 'readyToDispatch' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'roles' : Array<AppRole> }
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'assignAppRoles' : ActorMethod<[Principal, Array<AppRole>], undefined>,
  'createCustomer' : ActorMethod<
    [string, string, string, string, string, string],
    Customer
  >,
  'createDeliveryChallan' : ActorMethod<
    [string, string, string, string, string],
    DeliveryChallan
  >,
  'createEmployeeProfile' : ActorMethod<[EmployeeProfile], undefined>,
  'createEnquiry' : ActorMethod<
    [string, string, string, string, Time],
    Enquiry
  >,
  'createInvoice' : ActorMethod<[string, string, string], Invoice>,
  'createJobCard' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    JobCard
  >,
  'createMaterialRequisition' : ActorMethod<
    [string, string, string, string, bigint],
    MaterialRequisition
  >,
  'createPayment' : ActorMethod<[string, string, bigint, Time], Payment>,
  'createPurchaseOrder' : ActorMethod<
    [string, string, string, string, Time, bigint],
    PurchaseOrder
  >,
  'createQuotation' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<QuotationLineItem>,
      bigint,
      bigint,
      bigint,
      bigint,
      Time,
      string,
    ],
    Quotation
  >,
  'createSalesOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<SalesOrderLineItem>,
      Time,
      string,
    ],
    SalesOrder
  >,
  'fileExists' : ActorMethod<[string], boolean>,
  'generateDocNo' : ActorMethod<[string], string>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDeliveryChallans' : ActorMethod<[], Array<DeliveryChallan>>,
  'getAllEmployeeProfiles' : ActorMethod<[], Array<EmployeeProfile>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllJobCards' : ActorMethod<[], Array<JobCard>>,
  'getAllMaterialRequisitions' : ActorMethod<[], Array<MaterialRequisition>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getAllQuotations' : ActorMethod<[], Array<Quotation>>,
  'getAllSalesOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getDeliveryChallan' : ActorMethod<[string], [] | [DeliveryChallan]>,
  'getEmployeeProfile' : ActorMethod<[string], [] | [EmployeeProfile]>,
  'getEnquiry' : ActorMethod<[string], [] | [Enquiry]>,
  'getInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getJobCard' : ActorMethod<[string], [] | [JobCard]>,
  'getMaterialRequisition' : ActorMethod<[string], [] | [MaterialRequisition]>,
  'getPayment' : ActorMethod<[string], [] | [Payment]>,
  'getPurchaseOrder' : ActorMethod<[string], [] | [PurchaseOrder]>,
  'getQuotation' : ActorMethod<[string], [] | [Quotation]>,
  'getSalesOrder' : ActorMethod<[string], [] | [SalesOrder]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasDrawing' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEmployeeProfile' : ActorMethod<[string, EmployeeProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];