// §11/§12 — a real, programmatically-generated binary PDF (via jsPDF) with
// an embedded QR code (via the qrcode package), not a browser-print-to-PDF
// flow. These are the only two places in the whole QMS module that use
// these two dependencies — every other export/print flow in this app
// (Invoices, Quotations, this same Inspection Sheet's "Print" button)
// keeps using the existing window.print() technique untouched.
import jsPDF from "jspdf";
import QRCode from "qrcode";
import {
  INSPECTION_MODE_LABELS,
  INSPECTION_SHEET_STATUS_LABELS,
} from "../constants";
import {
  type InspectionSheet,
  type InspectionStageCompletion,
  type InspectionStageDefinition,
  type InspectionStageEntry,
  type QualityCharacteristic,
  revisionToLetter,
} from "../types";

export interface InspectionPdfInput {
  sheet: InspectionSheet;
  projectNo: string;
  customerName: string;
  companyName: string;
  companyAddress?: string;
  companyGstin?: string;
  companyLogoDataUrl?: string;
  stages: InspectionStageDefinition[];
  characteristicsByStage: Record<string, QualityCharacteristic[]>;
  entriesByStage: Record<string, InspectionStageEntry[]>;
  completionsByStage: Record<string, InspectionStageCompletion | undefined>;
}

/** What the QR code encodes. There's no URL routing in this SPA to deep-link
 * to, so it encodes a resolvable identifier instead — the Inspection Sheets
 * list page's search box finds a sheet by this exact string (§12: "scanning
 * opens the inspection viewer" — the practical equivalent when a camera scan
 * can't open an app route directly). */
export function qrPayloadForSheet(sheet: InspectionSheet): string {
  return `${sheet.inspectionNumber}`;
}

export async function generateInspectionPdf(
  input: InspectionPdfInput,
): Promise<Blob> {
  const { sheet } = input;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 15;
  const bottomLimit = pageHeight - 18;
  let y = 15;
  let pageNum = 1;

  const qrDataUrl = await QRCode.toDataURL(qrPayloadForSheet(sheet), {
    margin: 1,
    width: 200,
  });

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(`Page ${pageNum}`, pageWidth - marginX, pageHeight - 10, {
      align: "right",
    });
    doc.text(
      `Generated ${new Date().toLocaleString()}`,
      marginX,
      pageHeight - 10,
    );
    doc.text(
      `${input.companyName || "FabFlow"} — Quality Record`,
      pageWidth / 2,
      pageHeight - 10,
      {
        align: "center",
      },
    );
    doc.setTextColor(0);
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > bottomLimit) {
      addFooter();
      doc.addPage();
      pageNum++;
      y = 15;
    }
  };

  // ── Header ──────────────────────────────────────────────
  const logoWidth = input.companyLogoDataUrl ? 22 : 0;
  if (input.companyLogoDataUrl) {
    try {
      doc.addImage(input.companyLogoDataUrl, "PNG", marginX, y, 20, 20);
    } catch {
      // malformed/unsupported logo data — skip it rather than fail the whole export
    }
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(
    input.companyName || "Your Company",
    marginX + logoWidth + (logoWidth ? 4 : 0),
    y + 6,
  );
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  if (input.companyAddress) {
    doc.text(
      input.companyAddress,
      marginX + logoWidth + (logoWidth ? 4 : 0),
      y + 11,
    );
  }
  if (input.companyGstin) {
    doc.text(
      `GSTIN: ${input.companyGstin}`,
      marginX + logoWidth + (logoWidth ? 4 : 0),
      y + 15,
    );
  }

  doc.addImage(qrDataUrl, "PNG", pageWidth - marginX - 22, y, 22, 22);

  y += 26;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("QUALITY INSPECTION SHEET", marginX, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Inspection No: ${sheet.inspectionNumber}    Revision: ${revisionToLetter(sheet.revision)}    Status: ${INSPECTION_SHEET_STATUS_LABELS[sheet.status]}`,
    marginX,
    y,
  );
  y += 6;
  doc.setDrawColor(60);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 6;

  // ── Master document fields ─────────────────────────────
  const infoRows: Array<[string, string]> = [
    ["Project", input.projectNo],
    ["Customer", input.customerName],
    [
      "Drawing No / Rev",
      `${sheet.drawingReference || "—"} / ${sheet.drawingRevision || "—"}`,
    ],
    ["Mode", INSPECTION_MODE_LABELS[sheet.mode]],
    [
      "Generated By / Date",
      `${sheet.generatedBy} / ${new Date(sheet.generatedAt).toLocaleString()}`,
    ],
  ];
  doc.setFontSize(9);
  for (const [label, value] of infoRows) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, marginX, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, marginX + 42, y);
    y += 5;
  }
  y += 3;

  // ── Stages ──────────────────────────────────────────────
  for (const stage of input.stages) {
    ensureSpace(16);
    doc.setFillColor(235, 235, 235);
    doc.rect(marginX, y, pageWidth - marginX * 2, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(stage.name, marginX + 2, y + 5);
    y += 10;

    const chars = input.characteristicsByStage[stage.id] ?? [];
    const stageEntries = input.entriesByStage[stage.id] ?? [];

    if (chars.length === 0) {
      ensureSpace(6);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.text(
        "No characteristics defined for this stage in the library.",
        marginX + 2,
        y,
      );
      y += 6;
    }

    for (const c of chars) {
      ensureSpace(10);
      const entry = stageEntries.find((e) => e.characteristicId === c.id);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.text(c.name, marginX + 2, y);
      doc.setFont("helvetica", "normal");
      doc.text(`Result: ${entry?.result ?? "Pending"}`, marginX + 95, y);
      if (entry?.measuredValue) {
        doc.text(
          `Value: ${entry.measuredValue}${c.unit ? ` ${c.unit}` : ""}`,
          marginX + 140,
          y,
        );
      }
      y += 4.2;
      if (entry?.remarks) {
        ensureSpace(5);
        doc.setFontSize(7.5);
        doc.setTextColor(100);
        doc.text(`Remarks: ${entry.remarks}`, marginX + 4, y);
        doc.setTextColor(0);
        y += 4;
      }
    }

    const completion = input.completionsByStage[stage.id];
    ensureSpace(12);
    doc.setFontSize(7.5);
    doc.setTextColor(90);
    doc.text(
      `Inspector: ${completion?.inspectorName ?? "________________"}    Date: ${
        completion?.completedAt
          ? new Date(completion.completedAt).toLocaleString()
          : "________"
      }`,
      marginX + 2,
      y,
    );
    doc.setTextColor(0);
    y += 4;
    if (completion?.signatureDataUrl) {
      try {
        doc.addImage(
          completion.signatureDataUrl,
          "PNG",
          marginX + 2,
          y,
          28,
          10,
        );
        y += 12;
      } catch {
        y += 2;
      }
    } else {
      y += 2;
    }
    y += 4;
  }

  // ── Approval block ──────────────────────────────────────
  ensureSpace(20);
  doc.setDrawColor(140);
  doc.line(marginX, y, marginX + 52, y);
  doc.line(marginX + 62, y, marginX + 122, y);
  doc.line(marginX + 132, y, pageWidth - marginX, y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.text("Inspected By / Date", marginX, y);
  doc.text("Reviewed By (Supervisor) / Date", marginX + 62, y);
  doc.text("Approved By (QA Manager) / Date", marginX + 132, y);

  addFooter();

  return doc.output("blob");
}
