/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DeliveryChallan {
    id: string;
    status: string;
    dcNo: string;
    createdAt: Time;
    soId: string;
    customerId: string;
    items: string;
}
export type Time = bigint;
export interface MaterialRequisition {
    id: string;
    totalEstimatedCost: bigint;
    status: string;
    mrNo: string;
    createdAt: Time;
    jobId: string;
    items: string;
}
export interface SalesOrderLineItem {
    qty: bigint;
    desc: string;
    unitPrice: bigint;
    amount: bigint;
}
export interface SalesOrder {
    id: string;
    status: SalesOrderStatus;
    lineItems: Array<SalesOrderLineItem>;
    createdAt: Time;
    poId: string;
    qtId: string;
    soNo: string;
    deliveryDate: Time;
    customerId: string;
    remarks: string;
}
export interface JobCard {
    id: string;
    drawingFileIds: Array<string>;
    jobDescription: string;
    createdAt: Time;
    soId: string;
    jobNo: string;
    customerId: string;
    materialRequisitionStatus: string;
}
export interface Payment {
    id: string;
    createdAt: Time;
    invoiceId: string;
    paymentDate: Time;
    amount: bigint;
}
export interface Invoice {
    id: string;
    status: string;
    createdAt: Time;
    customerId: string;
    invNo: string;
}
export interface Enquiry {
    id: string;
    status: EnquiryStatus;
    createdAt: Time;
    description: string;
    enqNo: string;
    targetDate: Time;
    customerId: string;
    items: string;
}
export interface Customer {
    id: string;
    name: string;
    createdAt: Time;
    contactPerson: string;
    email: string;
    gstin: string;
    address: string;
    phone: string;
}
export interface QuotationLineItem {
    hsn: string;
    qty: bigint;
    desc: string;
    unitPrice: bigint;
    amount: bigint;
}
export interface Quotation {
    id: string;
    status: QuotationStatus;
    lineItems: Array<QuotationLineItem>;
    terms: string;
    createdAt: Time;
    qtNo: string;
    enqId: string;
    gstAmount: bigint;
    totalAmount: bigint;
    customerId: string;
    gstRate: bigint;
    validUntil: Time;
    subtotal: bigint;
}
export interface EmployeeProfile {
    name: string;
    photo?: Uint8Array;
    roles: Array<AppRole>;
}
export interface PurchaseOrder {
    id: string;
    status: PurchaseOrderStatus;
    poAmount: bigint;
    createdAt: Time;
    qtId: string;
    customerId: string;
    poRef: string;
    poDate: Time;
}
export interface UserProfile {
    name: string;
    roles: Array<AppRole>;
}
export enum AppRole {
    qc = "qc",
    admin = "admin",
    production = "production",
    sales = "sales",
    accounts = "accounts"
}
export enum EnquiryStatus {
    new_ = "new",
    closed = "closed",
    quoted = "quoted",
    inProgress = "inProgress"
}
export enum PurchaseOrderStatus {
    cancelled = "cancelled",
    confirmed = "confirmed",
    received = "received"
}
export enum QuotationStatus {
    sent = "sent",
    rejected = "rejected",
    accepted = "accepted",
    draft = "draft"
}
export enum SalesOrderStatus {
    closed = "closed",
    open = "open",
    dispatched = "dispatched",
    inProduction = "inProduction",
    readyToDispatch = "readyToDispatch"
}
export interface backendInterface {
    addAdmin(user: Principal): Promise<void>;
    assignAppRoles(user: Principal, roles: Array<AppRole>): Promise<void>;
    createCustomer(name: string, contactPerson: string, phone: string, email: string, address: string, gstin: string): Promise<Customer>;
    createDeliveryChallan(id: string, dcNo: string, soId: string, customerId: string, items: string): Promise<DeliveryChallan>;
    createEmployeeProfile(profile: EmployeeProfile): Promise<void>;
    createEnquiry(enqNo: string, customerId: string, description: string, items: string, targetDate: Time): Promise<Enquiry>;
    createInvoice(id: string, invNo: string, customerId: string): Promise<Invoice>;
    createJobCard(id: string, jobNo: string, soId: string, customerId: string, jobDescription: string, drawingFileIds: Array<string>): Promise<JobCard>;
    createMaterialRequisition(id: string, mrNo: string, jobId: string, items: string, totalEstimatedCost: bigint): Promise<MaterialRequisition>;
    createPayment(id: string, invoiceId: string, amount: bigint, paymentDate: Time): Promise<Payment>;
    createPurchaseOrder(id: string, poRef: string, qtId: string, customerId: string, poDate: Time, poAmount: bigint): Promise<PurchaseOrder>;
    createQuotation(id: string, qtNo: string, enqId: string, customerId: string, lineItems: Array<QuotationLineItem>, subtotal: bigint, gstRate: bigint, gstAmount: bigint, totalAmount: bigint, validUntil: Time, terms: string): Promise<Quotation>;
    createSalesOrder(id: string, soNo: string, poId: string, customerId: string, qtId: string, lineItems: Array<SalesOrderLineItem>, deliveryDate: Time, remarks: string): Promise<SalesOrder>;
    fileExists(_fileName: string): Promise<boolean>;
    generateDocNo(prefix: string): Promise<string>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllDeliveryChallans(): Promise<Array<DeliveryChallan>>;
    getAllEmployeeProfiles(): Promise<Array<EmployeeProfile>>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllJobCards(): Promise<Array<JobCard>>;
    getAllMaterialRequisitions(): Promise<Array<MaterialRequisition>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    getAllQuotations(): Promise<Array<Quotation>>;
    getAllSalesOrders(): Promise<Array<SalesOrder>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCustomer(customerId: string): Promise<Customer | null>;
    getDeliveryChallan(dcId: string): Promise<DeliveryChallan | null>;
    getEmployeeProfile(employeeId: string): Promise<EmployeeProfile | null>;
    getEnquiry(enquiryId: string): Promise<Enquiry | null>;
    getInvoice(invoiceId: string): Promise<Invoice | null>;
    getJobCard(jobId: string): Promise<JobCard | null>;
    getMaterialRequisition(mrId: string): Promise<MaterialRequisition | null>;
    getPayment(paymentId: string): Promise<Payment | null>;
    getPurchaseOrder(poId: string): Promise<PurchaseOrder | null>;
    getQuotation(quotationId: string): Promise<Quotation | null>;
    getSalesOrder(soId: string): Promise<SalesOrder | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasDrawing(_fileName: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEmployeeProfile(employeeId: string, profile: EmployeeProfile): Promise<void>;
}
import type { AppRole as _AppRole, Customer as _Customer, DeliveryChallan as _DeliveryChallan, EmployeeProfile as _EmployeeProfile, Enquiry as _Enquiry, EnquiryStatus as _EnquiryStatus, Invoice as _Invoice, JobCard as _JobCard, MaterialRequisition as _MaterialRequisition, Payment as _Payment, PurchaseOrder as _PurchaseOrder, PurchaseOrderStatus as _PurchaseOrderStatus, Quotation as _Quotation, QuotationLineItem as _QuotationLineItem, QuotationStatus as _QuotationStatus, SalesOrder as _SalesOrder, SalesOrderLineItem as _SalesOrderLineItem, SalesOrderStatus as _SalesOrderStatus, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async assignAppRoles(arg0: Principal, arg1: Array<AppRole>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAppRoles(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAppRoles(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createDeliveryChallan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<DeliveryChallan> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeliveryChallan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeliveryChallan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createEmployeeProfile(arg0: EmployeeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployeeProfile(to_candid_EmployeeProfile_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployeeProfile(to_candid_EmployeeProfile_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<Enquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.createEnquiry(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Enquiry_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEnquiry(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Enquiry_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: string, arg1: string, arg2: string): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2);
            return result;
        }
    }
    async createJobCard(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<JobCard> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobCard(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobCard(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createMaterialRequisition(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<MaterialRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterialRequisition(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterialRequisition(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPayment(arg0: string, arg1: string, arg2: bigint, arg3: Time): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPurchaseOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: bigint): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_PurchaseOrder_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_PurchaseOrder_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuotation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<QuotationLineItem>, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: Time, arg10: string): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return from_candid_Quotation_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return from_candid_Quotation_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSalesOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<SalesOrderLineItem>, arg6: Time, arg7: string): Promise<SalesOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_SalesOrder_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_SalesOrder_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async fileExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.fileExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileExists(arg0);
            return result;
        }
    }
    async generateDocNo(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDocNo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDocNo(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllDeliveryChallans(): Promise<Array<DeliveryChallan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryChallans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryChallans();
            return result;
        }
    }
    async getAllEmployeeProfiles(): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeeProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeeProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllJobCards(): Promise<Array<JobCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobCards();
            return result;
        }
    }
    async getAllMaterialRequisitions(): Promise<Array<MaterialRequisition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaterialRequisitions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaterialRequisitions();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return result;
        }
    }
    async getAllPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchaseOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchaseOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuotations(): Promise<Array<Quotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotations();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotations();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalesOrders(): Promise<Array<SalesOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesOrders();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesOrders();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryChallan(arg0: string): Promise<DeliveryChallan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryChallan(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryChallan(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeProfile(arg0: string): Promise<EmployeeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiry(arg0: string): Promise<Enquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiry(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiry(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobCard(arg0: string): Promise<JobCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobCard(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobCard(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialRequisition(arg0: string): Promise<MaterialRequisition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialRequisition(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialRequisition(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: string): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseOrder(arg0: string): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrder(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrder(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotation(arg0: string): Promise<Quotation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotation(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotation(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesOrder(arg0: string): Promise<SalesOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesOrder(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesOrder(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasDrawing(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasDrawing(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployeeProfile(arg0: string, arg1: EmployeeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeProfile(arg0, to_candid_EmployeeProfile_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeProfile(arg0, to_candid_EmployeeProfile_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AppRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeProfile): EmployeeProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EnquiryStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnquiryStatus): EnquiryStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Enquiry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrderStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrderStatus): PurchaseOrderStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationStatus): QuotationStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrderStatus): SalesOrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrder_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrder): SalesOrder {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeliveryChallan]): DeliveryChallan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeProfile]): EmployeeProfile | null {
    return value.length === 0 ? null : from_candid_EmployeeProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Enquiry]): Enquiry | null {
    return value.length === 0 ? null : from_candid_Enquiry_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobCard]): JobCard | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MaterialRequisition]): MaterialRequisition | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseOrder]): PurchaseOrder | null {
    return value.length === 0 ? null : from_candid_PurchaseOrder_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quotation]): Quotation | null {
    return value.length === 0 ? null : from_candid_Quotation_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesOrder]): SalesOrder | null {
    return value.length === 0 ? null : from_candid_SalesOrder_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PurchaseOrderStatus;
    poAmount: bigint;
    createdAt: _Time;
    qtId: string;
    customerId: string;
    poRef: string;
    poDate: _Time;
}): {
    id: string;
    status: PurchaseOrderStatus;
    poAmount: bigint;
    createdAt: Time;
    qtId: string;
    customerId: string;
    poRef: string;
    poDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_PurchaseOrderStatus_n12(_uploadFile, _downloadFile, value.status),
        poAmount: value.poAmount,
        createdAt: value.createdAt,
        qtId: value.qtId,
        customerId: value.customerId,
        poRef: value.poRef,
        poDate: value.poDate
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _QuotationStatus;
    lineItems: Array<_QuotationLineItem>;
    terms: string;
    createdAt: _Time;
    qtNo: string;
    enqId: string;
    gstAmount: bigint;
    totalAmount: bigint;
    customerId: string;
    gstRate: bigint;
    validUntil: _Time;
    subtotal: bigint;
}): {
    id: string;
    status: QuotationStatus;
    lineItems: Array<QuotationLineItem>;
    terms: string;
    createdAt: Time;
    qtNo: string;
    enqId: string;
    gstAmount: bigint;
    totalAmount: bigint;
    customerId: string;
    gstRate: bigint;
    validUntil: Time;
    subtotal: bigint;
} {
    return {
        id: value.id,
        status: from_candid_QuotationStatus_n16(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        terms: value.terms,
        createdAt: value.createdAt,
        qtNo: value.qtNo,
        enqId: value.enqId,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        gstRate: value.gstRate,
        validUntil: value.validUntil,
        subtotal: value.subtotal
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SalesOrderStatus;
    lineItems: Array<_SalesOrderLineItem>;
    createdAt: _Time;
    poId: string;
    qtId: string;
    soNo: string;
    deliveryDate: _Time;
    customerId: string;
    remarks: string;
}): {
    id: string;
    status: SalesOrderStatus;
    lineItems: Array<SalesOrderLineItem>;
    createdAt: Time;
    poId: string;
    qtId: string;
    soNo: string;
    deliveryDate: Time;
    customerId: string;
    remarks: string;
} {
    return {
        id: value.id,
        status: from_candid_SalesOrderStatus_n20(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        createdAt: value.createdAt,
        poId: value.poId,
        qtId: value.qtId,
        soNo: value.soNo,
        deliveryDate: value.deliveryDate,
        customerId: value.customerId,
        remarks: value.remarks
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    photo: [] | [Uint8Array];
    roles: Array<_AppRole>;
}): {
    name: string;
    photo?: Uint8Array;
    roles: Array<AppRole>;
} {
    return {
        name: value.name,
        photo: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.photo)),
        roles: from_candid_vec_n26(_uploadFile, _downloadFile, value.roles)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    roles: Array<_AppRole>;
}): {
    name: string;
    roles: Array<AppRole>;
} {
    return {
        name: value.name,
        roles: from_candid_vec_n26(_uploadFile, _downloadFile, value.roles)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EnquiryStatus;
    createdAt: _Time;
    description: string;
    enqNo: string;
    targetDate: _Time;
    customerId: string;
    items: string;
}): {
    id: string;
    status: EnquiryStatus;
    createdAt: Time;
    description: string;
    enqNo: string;
    targetDate: Time;
    customerId: string;
    items: string;
} {
    return {
        id: value.id,
        status: from_candid_EnquiryStatus_n8(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        description: value.description,
        enqNo: value.enqNo,
        targetDate: value.targetDate,
        customerId: value.customerId,
        items: value.items
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
} | {
    received: null;
}): PurchaseOrderStatus {
    return "cancelled" in value ? PurchaseOrderStatus.cancelled : "confirmed" in value ? PurchaseOrderStatus.confirmed : "received" in value ? PurchaseOrderStatus.received : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    draft: null;
}): QuotationStatus {
    return "sent" in value ? QuotationStatus.sent : "rejected" in value ? QuotationStatus.rejected : "accepted" in value ? QuotationStatus.accepted : "draft" in value ? QuotationStatus.draft : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    dispatched: null;
} | {
    inProduction: null;
} | {
    readyToDispatch: null;
}): SalesOrderStatus {
    return "closed" in value ? SalesOrderStatus.closed : "open" in value ? SalesOrderStatus.open : "dispatched" in value ? SalesOrderStatus.dispatched : "inProduction" in value ? SalesOrderStatus.inProduction : "readyToDispatch" in value ? SalesOrderStatus.readyToDispatch : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qc: null;
} | {
    admin: null;
} | {
    production: null;
} | {
    sales: null;
} | {
    accounts: null;
}): AppRole {
    return "qc" in value ? AppRole.qc : "admin" in value ? AppRole.admin : "production" in value ? AppRole.production : "sales" in value ? AppRole.sales : "accounts" in value ? AppRole.accounts : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    quoted: null;
} | {
    inProgress: null;
}): EnquiryStatus {
    return "new" in value ? EnquiryStatus.new : "closed" in value ? EnquiryStatus.closed : "quoted" in value ? EnquiryStatus.quoted : "inProgress" in value ? EnquiryStatus.inProgress : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeProfile>): Array<EmployeeProfile> {
    return value.map((x)=>from_candid_EmployeeProfile_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppRole>): Array<AppRole> {
    return value.map((x)=>from_candid_AppRole_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quotation>): Array<Quotation> {
    return value.map((x)=>from_candid_Quotation_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesOrder>): Array<SalesOrder> {
    return value.map((x)=>from_candid_SalesOrder_n18(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeProfile): _EmployeeProfile {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    roles: Array<AppRole>;
}): {
    name: string;
    roles: Array<_AppRole>;
} {
    return {
        name: value.name,
        roles: to_candid_vec_n1(_uploadFile, _downloadFile, value.roles)
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    photo?: Uint8Array;
    roles: Array<AppRole>;
}): {
    name: string;
    photo: [] | [Uint8Array];
    roles: Array<_AppRole>;
} {
    return {
        name: value.name,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        roles: to_candid_vec_n1(_uploadFile, _downloadFile, value.roles)
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    qc: null;
} | {
    admin: null;
} | {
    production: null;
} | {
    sales: null;
} | {
    accounts: null;
} {
    return value == AppRole.qc ? {
        qc: null
    } : value == AppRole.admin ? {
        admin: null
    } : value == AppRole.production ? {
        production: null
    } : value == AppRole.sales ? {
        sales: null
    } : value == AppRole.accounts ? {
        accounts: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AppRole>): Array<_AppRole> {
    return value.map((x)=>to_candid_AppRole_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
